name: Discord notifications

on: [push, pull_request_target]

jobs:
  notify_discord:
    runs-on: ubuntu-22.04
    if: always() && github.repository == 'SerenityOS/serenity' && (github.event_name == 'pull_request_target' || (github.event_name == 'push' && github.ref == 'refs/heads/master'))

    steps:
      - name: Discord action notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          CUSTOM_GITHUB_EVENT_NAME: ${{ github.event_name == 'pull_request_target' && 'pull_request' || github.event_name }} # fake the event type as discord doesn't know how to parse the special pull_request_target context
        uses: IdanHo/action-discord@754598254f288e6d8e9fca637832e3c163515ba8
        # FIXME: Find a way to notify on 'ready_for_review', but rate-limited to once/twice per day.
        if: ${{ (github.event['pull_request'] && github.event['action'] == 'opened') || github.event['commits'] }}
