name: Generate man pages

on:
  push:
    paths:
      - "Base/usr/share/man/**"
      - "Meta/Websites/man.serenityos.org/**"

jobs:
  convert_using_pandoc:
    runs-on: ubuntu-22.04
    if: always() && github.repository == 'SerenityOS/serenity' && github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.13'
      - name: Actually build website
        run: ./Meta/build-manpages-website.sh
      - name: Deploy to GitHub pages
        uses: JamesIves/github-pages-deploy-action@v4.6.9
        with:
          git-config-name: BuggieBot
          git-config-email: buggiebot@serenityos.org
          branch: master
          repository-name: SerenityOS/manpages-website
          token: ${{ secrets.BUGGIEBOT_TOKEN }}
          folder: output
